dsa/urls.py
from django.urls import path
from . import views
from website.views import *


urlpatterns = [
	path('dashboard/', views.dsa_dashboard, name='dashboard'),
    path('login/', views.dsa_login, name='dsalogin'),
    path('logout/', views.dsa_logout, name= 'logout'),
    path('signup/', views.dsa_Signup, name='dsasignup'),
    # path('activate/<uidb64>/<token>/',views.activate, name='activate'),
]

sanctitty/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('dsa/', include('dsa.urls')),
]

handler404 = 'website.views.custom_page_not_found_view'
handler500 = 'website.views.custom_error_view'
# handler403 = 'my_app_name.views.custom_permission_denied_view'
# handler400 = 'my_app_name.views.custom_bad_request_view'

dsa/models.py
from django.db import models
from .models import *
from website.models import *
# Create your models here.
class DSA(Basic_Details):
    education = models.CharField(max_length=200, null=True, blank=True)
    referral_id = models.CharField(max_length=15, null=True, blank=True)
    referred_by = models.CharField(max_length=15, null=True, blank=True)
    approved = models.BooleanField(default=False, null=False)

website/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
# from .validators import validate_file

class Basic_Details(models.Model):
    #Basic details component

    GENDER_CHOICES = [
    ("Male", ("Male")),
    ("Female", ("Female")),
    ("Other", ("Other"))
    ]
    
    #basic info
    entry_date = models.DateField(default=timezone.now)
    created_time = models.TimeField(default=timezone.now)
    # account holder info 

    first_name = models.CharField(max_length=100,null = True)
    last_name = models.CharField(max_length=100,null = True)
    gender = models.CharField(max_length=10,null = True,choices=GENDER_CHOICES, blank=False)
    father_name = models.CharField(max_length= 100, null=True)
    mother_name = models.CharField(max_length= 100, null=True , blank =True)
    date_of_birth = models.DateField(blank=True,null = True)

    # account holder address info
    current_address = models.TextField(null=True )
    
    city = models.CharField(max_length= 100, null=True  )
    district = models.CharField(max_length= 100, null=True  )
    state = models.CharField(max_length= 100, null=True  )
    pincode = models.CharField(max_length= 100, null=True  )
    country = models.CharField(max_length= 100, null=True)
      
    email_id = models.EmailField(max_length = 100 , null =True, blank = True)
    permanent_address = models.TextField(null=True )
    mobile_number_1 = models.CharField(max_length = 10, null=True )
    mobile_number_2 = models.CharField(max_length = 10, null=True, blank =True)

    # id proof component
    pan = models.CharField(max_length=200, null=True, blank=True)
    aadhar = models.CharField(max_length=200, null=True, blank=True)
    pan_image = models.FileField(upload_to='pan/', null=True, blank=True)
    aadhar_front = models.FileField(upload_to='aadhar_f/', null=True, blank=True)
    aadhar_back = models.FileField(upload_to='aadhar_b/', null=True, blank=True)
    user_image = models.ImageField(upload_to='user_image/', null=True, blank=False)

    # extra fields for DSA form
    dsa_experience = models.IntegerField(null=True, blank=True)
    business_name  = models.CharField(max_length=200, null=True, blank=False)
    pan_or_aadhar  = models.FileField(null=True, blank=False, upload_to='dsa_docs/')


    

    def save(self, *args, **kwargs):
        self.first_name = self.first_name.title() 
        self.last_name = self.last_name.title() if(self.last_name) else self.last_name
        self.father_name = self.father_name.title() if(self.father_name) else self.father_name
        self.mother_name = self.mother_name.title() if(self.mother_name) else self.mother_name
        self.current_address = self.current_address.title() if(self.current_address) else self.current_address 
        self.permanent_address = self.permanent_address.title() if(self.permanent_address) else self.permanent_address
        super(Basic_Details, self).save(*args, **kwargs)


class Bank_Details(models.Model):
    name = models.CharField(max_length=200, null=True, blank=False)
    account_number = models.CharField(max_length=200, null=True, blank=False)
    IFSC_CODE = models.CharField(max_length=200, null=True, blank=False)

class PL_Docs(models.Model):
    salary_slip = models.FileField(upload_to='PL/salary_slip/', null=True, blank=True)
    bank_statement = models.FileField(upload_to='PL/bank_statement/', null=True, blank=True)
    residential_proof = models.FileField(upload_to='PL/res_proof/', null=True, blank=True)

class PL_reference(models.Model):
    RELATIONSHIP_CHOICES = [
        ("Father", ("Father")),
        ("Mother", ("Mother")),
        ("Brother", ("Brother")),
        ("Sister", ("Sister")),
    ]
    ref_1_name = models.CharField(max_length=200, null=True, blank=False)
    ref_2_name = models.CharField(max_length=200, null=True, blank=False)
    ref_1_contact = models.CharField(max_length=200, null=True, blank=False)
    ref_2_contact = models.CharField(max_length=200, null=True, blank=False)
    ref_1_relationship = models.CharField(max_length=200, null=True, blank=False)
    ref_2_relationship = models.CharField(max_length=200, null=True, blank=False)

class PL(Basic_Details):
    PROPERTY_CHOICES = [
    ("Rented", ("Rented")),
    ("Leased", ("Leased")),
    ("Self", ("Self")),
    ("Other", ("Other"))
    ]
    EMPLOYMENT_CHOICES = [
    ("Salaried", ("Salaried")),
    ("Self-Employed", ("Self-Employed")),
    ("Self", ("Self")),
    ("Other", ("Other"))
    ]
    EDUCATION_CHOICES = [
    ("10th", ("10th")),
    ("10+2", ("10+2")),
    ("Graduate", ("Graduate")),
    ("Post-Graduate", ("Post-Graduate"))
    ]
    newsletter = models.BooleanField(default=True, null=False)
    education = models.CharField(max_length=20,null = True,choices=EDUCATION_CHOICES,  blank=False )
    married = models.BooleanField(default=False)
    property_ownership_status = models.CharField(max_length=20,null = True, choices=PROPERTY_CHOICES,  blank=False)
    no_of_years_at_residence = models.IntegerField(null=True, blank=True)
    employment_type = models.CharField(max_length=15,null = True,choices=EMPLOYMENT_CHOICES,  blank=False)
    bank_details = models.ForeignKey(Bank_Details, on_delete=models.CASCADE, null=True)
    docs = models.ForeignKey(PL_Docs, on_delete=models.CASCADE, null=True)
    references = models.ForeignKey(PL_reference, on_delete=models.CASCADE, null=True)

        

class Contact(models.Model):
    #basic info
    created_time = models.DateField(default=timezone.now)
    name = models.CharField(max_length=200,null = True,blank=True)
    email = models.CharField(max_length=200,null = True,blank=True)
    phone = models.CharField(max_length=200,null = True,blank=True)
    message = models.TextField(null=True, blank=True)


class Business_Loan(models. Model):
    firstName       =    models.CharField(max_length=30, null=True, blank=True)
    lastName        =    models.CharField(max_length=30, null=True, blank=True)
    contactNum      =    models.CharField(max_length=13, null=True, blank=True)

dsa/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate

# from dsa.models import *

class UserRegForm(UserCreationForm):
	email = forms.EmailField(max_length=100, help_text='Please enter a valid email address')
	

	class Meta(UserCreationForm):
		model = get_user_model()
		fields = ('email', 'password1', 'password2')

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		try:
			account = get_user_model().objects.get(email=email)
		except Exception as e:
			return email
		raise forms.ValidationError(f'Email {email} is already in use.')
		

class DsaAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label="Password", widget=forms.PasswordInput)

	class Meta:
		model  = get_user_model()
		fields = ("email", "password")

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError('Email or password is incorrect.')
		

dsa/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect

from django.contrib import messages
from django.urls import reverse
from dsa.forms import *
from django.contrib.auth.forms import AuthenticationForm
from website.forms import *
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from .models import *
from . forms import UserRegForm, DsaAuthenticationForm

from django.conf import settings

User = get_user_model()

def dsa_Signup(request):

    user = request.user
    if user.is_authenticated:
        return HttpResponse(f'You are already authenticated as {user.email}.')

    context = {}
    if request.method == 'POST':
        form       = UserRegForm(request.POST)

        if form.is_valid():
            form.save()
            email         = form.cleaned_data.get('email')
            raw_password  = form.cleaned_data.get('password1')
            user      = authenticate(email=email, password=raw_password)
            login(request,user)
            return redirect('dsalogin')
        else:
            context['form'] = form

    else:
        form = DSAForm()
        context['form'] = form
    return render(request, 'dsa/signup.html', context)


def dsa_login(request):

    context = {}

    user = request.user
    if user.is_authenticated:
        return redirect('dashboard')
    
    if request.method == 'POST':
        form = DsaAuthenticationForm(request.POST)
        if form.is_valid():
            email    = request.POST['email']
            password = request.POST['password']

            user = authenticate(email=email, password=password)
            print('dkafhd')

            if user is not None:
                login(request, user)
                messages.info(request, f'You are logged in as {email}')
                return redirect('dashboard')
            else:
                messages.error(request, 'Username or password is incorrect')

        else:
            print(form.errors)
            context['form'] = form
    else:
        # print('nice')
        form = DsaAuthenticationForm()
        context['form'] = form
    return render(request, 'dsa/login.html', context)


def dsa_logout(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("dsalogin")


@login_required
def dsa_dashboard(request):
    return render(request, 'dsa/dashboard.html')

dsa/templates/dsa/activation_request.html
{% autoescape off %}
Hi {{ user.username }},

Please click the following link to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

dsa/templates/dsa/activation_sent.html
<h3>Activation link sent! Please check your console or mail.</h3>

dsa/templates/dsa/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

<!-- meta tags -->
<meta charset="utf-8"/>
<meta name="keywords" content="finance, quick, loans, credit, personal loans" />
<meta name="description" content="Moneyply - Get your personal loan here" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

<!-- Title -->
<title>MP - DSA Portal</title>

<!-- Favicon Icon -->
<link rel="shortcut icon" href="{% static "website/images/FAVICON_NEW.png" %}" />

<!-- inject css start -->

<link href="{% static "website/css/theme-plugin.css"%}" rel="stylesheet" />
<link href="{% static "website/css/theme.min.css"%}" rel="stylesheet" />
<link href="{% static "website/css/custom.css"%}" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />

{% block my_css %}
{% endblock my_css %}

<!-- inject css end -->

</head>

<body>

<!-- page wrapper start -->

<div class="page-wrapper">
  
<!-- preloader start -->

{% include 'website/includes/_preloader.html' %}

<!-- preloader end -->


<!--header start-->



<!--header end-->





<!--body content start-->
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" id="msg">
  <strong>Message: </strong> {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

{% block content %}

{% endblock content %}



<!--body content end--> 


<!--footer start-->

{% include 'website/includes/_footer.html' %}

<!--footer end-->

</div>

<!-- page wrapper end -->

 
<!--back-to-top start-->

<div class="scroll-top"><a class="smoothscroll" href="#top"><i class="las la-angle-up"></i></a></div>

<!--back-to-top end-->

<!-- inject js start -->

<script src="{% static "website/js/theme-plugin.js"%}"></script>
<script src="{% static "website/js/theme-script.min.js"%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.matchHeight/0.7.2/jquery.matchHeight-min.js" integrity="sha512-/bOVV1DV1AQXcypckRwsR9ThoCj7FqTV2/0Bm79bL3YSyLkVideFLE3MIZkq1u5t28ke1c0n31WYCOrO01dsUg==" crossorigin="anonymous"></script>


<script type="text/javascript">
	setTimeout(function(){
		if ($('#msg').length>0){
			$('#msg').remove();
		}
	}, 4000)
</script>

{% block my_js %}
{% endblock my_js %}

<!-- inject js end -->

</body>

</html>

dsa/templates/dsa/dashboard.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

	<!-- Title -->
	<title>
		Dashboard
	</title>

	<!-- Favicon icon -->
	<link rel="shortcut icon" href="{% static "website/images/FAVICON_NEW.png" %}">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
	<!-- CSS start -->
	
	<!-- CSS end -->
</head>
<body>

	<div class="sidebar">
		<div class="sidebar-header">
			<h3 class="brand">
				<span class="ti-unlink"></span>
				<span>Moneyply</span>
			</h3> 
			<span class="ti-menu-alt"></span>
		</div>

		<div class="sidebar-menu">
			<ul>
				<li>
					<a href="">
						<span class="ti-home"></span>
						<span>Home</span>
					</a>
				</li>
				<li>
					<a href="">
						<span class="ti-documents"></span>
						<span></span>
					</a>
				</li>
			</ul>
		</div>
	</div>


<!-- JavaScript start -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<!-- JavaScript end -->

</body>
</html>

dsa/templates/dsa/dsa.html
{% extends 'website/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block my_css %}
<style>
  label {
    font-size: 0.8em;
  }
</style>

{% endblock my_css %}

{% block content %}

{% include 'website/includes/_navbar2.html' %}


<section class="position-relative" >
  <div id="particles-js"></div>
  <div class="container">
    <div class="row  text-center">
      <div class="col">
        <h1>Direct Service Agents</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb justify-content-center bg-transparent p-0 m-0">
            <li class="breadcrumb-item"><a class="text-dark" href="/">Home</a>
            </li>
            <li class="breadcrumb-item active text-primary" aria-current="page">DSA</li>
          </ol>
        </nav>
      </div>
    </div>
    <!-- / .row -->
  </div>
  <!-- / .container -->
</section>

<!--hero section end--> 


<!--body content start-->

<div class="page-content">

<!--about start-->

<section class="register">
  <div class="container">
     <div class="row justify-content-center text-center">
      <div class="col-lg-8 col-md-12">
        <div class="mb-6"> <span class="badge badge-primary-soft p-2">
                  <i class="la la-exclamation ic-3x rotation"></i>
              </span>
          <h2 class="mt-3">Join us as a DSA now!</h2>
        </div>
        </div>
        </div>
    <div class="row">
      <div class="col-lg-10 col-md-12 ml-auto mr-auto">
        <div class="register-form text-left">
          <form id="dsa-form" method="POST" enctype="multipart/form-data" novalidate="true" action="">
          {% csrf_token %}
            <!-- <div class="messages">
              {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                 <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
              </ul>
              {% endif %}
            </div> -->
            <div class="form-row">
              <div class="col-md-4">
                <div class="form-group">
                <label for="id_first_name">First Name</label>
                  {% render_field form.first_name class+="form-control" required="required" data-error="Firstname is required."  %}
                  <div class="help-block with-errors"></div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                <label for="id_last_name">Last Name</label>
                  {% render_field form.last_name class+="form-control" required="required" data-error="Lastname is required."  %}
                  <div class="help-block with-errors"></div>
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="col-md-4">
                <div class="form-group">
                <label for="id_email">Email</label>
                  {% render_field form.email_id type="email" class+="form-control" required="required" data-error="Please enter a valid email address."  %}
                  <div class="help-block with-errors"></div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                <label for="id_mobile_number_1">Contact Number</label>
                  {% render_field form.mobile_number_1 class+="form-control" required="required" data-error="Mobile Number is required."  %}
                  <div class="help-block with-errors"></div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                <label for="id_city">Business sourcing city </label>
                  {% render_field form.city class+="form-control" required="required" data-error="City/Village is required."  %}
                  <div class="help-block with-errors"></div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="id_experience">Years of experience as DSA</label>
                  {% render_field form.dsa_experience class+="form-control" required="required" data-error="This field is required."  %}
                  <div class="help-block with-errors"></div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="id_business_name">Name of agency</label>
                   {% render_field form.business_name class+="form-control" required="required" data-error="Business name is required."  %}
                  <div class="help-block with errors"></div>
                </div>
              </div>
              <div class="col-md-4">
                <div clas="form-group">
                  <label for="id_file">Aadhar or PAN card in pdf format</label>
                    {% render_field form.pan_or_aadhar class+="form-control" required="required" data-error="Business name is required." accept=".pdf"  %}
                </div>
              </div>
            </div>

            <div class="row mt-5">
              <div class="col-md-12">
                <div class="remember-checkbox clearfix mb-5">
                  <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="terms" name="terms" required="required" data-error="Please check this box for further processing"/>
                    <label class="custom-control-label" for="terms">I agree to the  <a href="/terms-conditions"> terms and conditions </a> and  <a href="/privacy-policy"> privacy policy </a></label>
                    <div style="display:none; color:red; font: small-caps; font-size: 15px;" id="agree_chk_error">
                            Please indicate if you agree with our terms and conditions and privacy-policy!
                    </div>
                  </div>
                </div> 
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <button type="submit" id="form-sub" class="btn btn-primary">Submit Application</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>


<section>
  <div class="container">
    <div class="row align-items-center justify-content-between">
      <div class="col-12 col-lg-12 col-xl-12 text-center">
        <div> <span class="badge badge-primary-soft p-2">
                  <i class="la la-exclamation ic-3x rotation"></i>
              </span>
          <h2 class="mt-3 font-w-5">MoneyPly Direct Service Agents</h2>
          <p class="lead">The job of a DSA is to find potential customers for the bank they represent. To do this, DSAs will look for people who are in the market for a loan. These leads are then directed to the concerned bank or NBFC and the loan process is taken forward. For the effort put in by the DSA, a payout is provided.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!--about end-->


<!--feature start-->

<section id="dsa-services">
  <div class="container">
  <h2 class="mt-3 mb-5 font-w-5 text-center">Why join us?</h2>
    <div class="row align-items-center">
      <div class="col-xl-4 col-lg-4 mb-8 mb-lg-0">
        <div class="px-4 py-7 rounded hover-translate text-center bg-white shadow">
          <div>
            <img class="img-fluid" src="{% static "website/images/illustrations/expen.svg"%}" alt="">
          </div>
          <h5 class="mt-4 mb-3">Additional Income</h5>
          <p>You can earn additional income. The amount you earn will vary from lead to lead.</p>
          <button type="button" class="btn btn-link p-0">Read Details</button>
        </div>
      </div>
      <div class="col-xl-4 col-lg-4 col-sm-6">
        <div class="px-4 py-7 rounded hover-translate text-center bg-white shadow">
          <div>
            <img class="img-fluid" src="{% static "website/images/illustrations/travellers.svg"%}" alt="">
          </div>
          <h5 class="mt-4 mb-3">Flexibility</h5>
          <p>Flexible working hours.</p>
          <button type="button" class="btn btn-link p-0">Read Details</button>
        </div>
      </div>
      <div class="col-xl-4 col-lg-4 col-sm-6 mt-6 mt-sm-0">
        <div class="px-4 py-7 rounded hover-translate text-center bg-white shadow">
          <div>
            <img class="img-fluid" src="{% static "website/images/illustrations/age.svg"%}" alt="">
          </div>
          <h5 class="mt-4 mb-3">Start Anytime</h5>
          <p>Higher education is not a requirement.</p>
          <button type="button" class="btn btn-link p-0">Read Details</button>
        </div>
      </div>
    </div>
    <div class="row align-items-center mt-lg-8">
      <div class="col-xl-4 col-lg-4 mb-8 mb-lg-0">
        <div class="px-4 py-7 rounded hover-translate text-center bg-white shadow">
          <div>
            <img class="img-fluid" src="{% static "website/images/illustrations/thinking.svg"%}" alt="">
          </div>
          <h5 class="mt-4 mb-3">No Prerequisites</h5>
          <p>Your training is generally provided by us</p>
          <button type="button" class="btn btn-link p-0">Read Details</button>
        </div>
      </div>
      <div class="col-xl-4 col-lg-4 col-sm-6">
        <div class="px-4 py-7 rounded hover-translate text-center bg-white shadow">
          <div>
            <img class="img-fluid" src="{% static "website/images/team/time.svg" %}" alt="">
          </div>
          <h5 class="mt-4 mb-3">Flexibility</h5>
          <p>Flexible working hours.</p>
          <button type="button" class="btn btn-link p-0">Read Details</button>
        </div>
      </div>
      <div class="col-xl-4 col-lg-4 col-sm-6 mt-6 mt-sm-0">
        <div class="px-4 py-7 rounded hover-translate text-center bg-white shadow">
          <div>
            <img class="img-fluid" src="{% static "website/images/illustrations/loan.svg"%}" alt="">
          </div>
          <h5 class="mt-4 mb-3">Minimum to No Risk</h5>
          <p>You can run your business with minimum cost with very little risk.</p>
          <button type="button" class="btn btn-link p-0">Read Details</button>
        </div>
      </div>
    </div>
    </div>
  </div>
</section>

<!--feature end-->
</div>
{% endblock content %}


{% block my_js %}
  <script type="text/javascript">
    $('#dsa-form').validator();
    $(function() {
      $('.hover-translate').matchHeight();
    });

    $("#dsa-form").on("submit",function(form){
      if(!$("#terms").prop("checked")){
        $("#agree_chk_error").show();
        return false;

      }
      else{
        $("#agree_chk_error").hide();
      }
      return true;
    })
  </script>

{% endblock my_js %}

dsa/templates/dsa/login.html
{% extends 'dsa/base.html' %}
{% load static %}

{% block content %}

{% include 'website/includes/_navbar2.html' %}

<section class="position-relative">
  <div id="particles-js"></div>
  <div class="container">
    <div class="row  text-center">
      <div class="col">
        <h1>Agent Login</h1>
      </div>
    </div>
    <!-- / .row -->
  </div>
  <!-- / .container -->
</section>

<!--hero section end--> 


<!--body content start-->

<div class="page-content">

<!--about start-->

<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-5">
        <div>
          <h2 class="text-center mb-3">Login please!</h2>
          <form id="contact-form" method="POST" novalidate="true">
          {% csrf_token %}
            <div class="messages"></div>
            <div class="form-group">
              <label>Email</label>
              <input id="loginemail" type="type" name="email" class="form-control" placeholder="Your_email@xyz.com" required="required" data-error="Email is required.">
              <div class="help-block with-errors"></div>
            </div>
            <div class="form-group">
              <label>Password</label>
              <input id="loginpass" type="password" name="password" class="form-control" placeholder="Password" required="required" data-error="password is required.">
              <div class="help-block with-errors"></div>
            </div>
            {% for field in login_form %}
            <p>
              {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
              {% endfor %}
            </p>
            {% endfor %}
            {% if login_form.non_field_errors %}
            <div style="color: red">
              <p>{{ login_form.non_field_errors }}</p>
            </div>
            {% endif %}
            <div class="form-group mt-4 mb-5">
              {% comment %} <div class="remember-checkbox d-flex align-items-center justify-content-between">
                <div class="checkbox">
                  <input type="checkbox" id="check2" name="check2">
                  <label for="check2">Remember me</label>
                </div>
                 <a href="#">Forgot Password?</a>
              </div> {% endcomment %}
            </div> <button type="submit" class="btn btn-primary btn-block">Login Now</button>
          </form>
          <p class="text-center">Don't have an account? <a href='/dsa/'>Create an account</a>.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!--about end-->

<!--client end-->

</div>
{% endblock content %}

dsa/templates/dsa/logout.html
{% extends 'dsa/base.html' %}
{% load static %}

{% block content %}

<h2>You have been logged out!</h2>
<div class="border-top pt-3">
	<small class="text-muted">
		<a href="{% url 'dsalogin' %}">Log In Again</a>
	</small>
</div>

{% endblock content %}